apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: testapp
  replicas: 2
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: crccheck/hello-world:v1.0.0
        ports:
        - containerPort: 8000